### ISSUE TITLE
Influx crashes after today's update

### ISSUE THREAD

**Issue by e-slut** [TotallyMehis/Influx-Timer#29]
Whenever I try to join my server it just crashes I don't even get a error log

EDIT:
Looks like influx_recording is causing the problem it's happening to other timers too.

**Comment by nknm** [comment]
yep i can confirm its only influx_recording.smx.

**Comment by TotallyMehis** [comment]
d36b668d3efdcc264b320fd943e499f96e2bfeac should fix it. SetClientInfo doesn't want to work, so this was a great opportunity to change it to SetClientName. Make sure you have auto-update on so you get the latest offsets.

**Comment by nknm** [comment]
now i can use the plugin but i dont have a bot in the server

**Comment by e-slut** [comment]
Still crashing got the latest version of Sourcemod. MythicalGaming got it working and they are using the same timer.

EDIT:
Never mind got it working

**Comment by nknm** [comment]
I got it working aswell

**Comment by nknm** [comment]
But i dont have a replay bot in the server #help

**Comment by e-slut** [comment]
Did you update gamedata?

**Comment by nknm** [comment]
Nope how's that

**Comment by e-slut** [comment]
Update it https://github.com/alliedmodders/sourcemod/blob/79970ca5fa4fc068e73c98d3ca1dc6440fcd104a/gamedata/sdktools.games/engine.csgo.txt

**Comment by nknm** [comment]
Can you add me on steam pls- /id/nknm

Edit: Still have no bots :(

**Comment by e-slut** [comment]
Sent it
